/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_OsKeyLocker_platform_windows_WindowsDPAPI */

#ifndef _Included_com_OsKeyLocker_platform_windows_WindowsDPAPI
#define _Included_com_OsKeyLocker_platform_windows_WindowsDPAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_OsKeyLocker_platform_windows_WindowsDPAPI
 * Method:    protect
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_OsKeyLocker_platform_windows_WindowsDPAPI_protect
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_OsKeyLocker_platform_windows_WindowsDPAPI
 * Method:    unprotect
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_OsKeyLocker_platform_windows_WindowsDPAPI_unprotect
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
